config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get 'welcome/home', to: 'welcome#home'
get 'welcome/about', to: 'welcome#about'
get 'pages/home', to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages Homes</h1>

<%= link_to 'Welcome/Home', welcome_home_path %>


<h1><%= link_to image_tag('stranger.jpg'), 'www.disney.com' %></h1>

app/views/welcome/about.html.erb
<h1>About</h1>


<%= link_to 'Home', welcome_home_path %>

app/views/welcome/home.html.erb
<h1>this home</h1>>


<%=  link_to 'About', welcome_about_path %>